services:
  - type: web
    name: archive-saver
    env: python
    buildCommand: |
      echo "✅ Step 1: Build frontend"
      cd frontend && npm install && npm run build

      echo "✅ Step 2: Install backend Python dependencies"
      cd ../backend
      pip install --upgrade pip
      pip install -r requirements.txt

      echo "✅ Step 3: Install Playwright browser"
      python -m playwright install chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    buildFilter:
      paths:
        - frontend/**
        - backend/**
        - render.yaml
