services:
  - type: web
    name: archive-saver
    env: python
    plan: free
    region: singapore
    buildCommand: |
      echo "✅ Step 1: Install frontend deps"
      cd frontend && npm install && npm run build

      echo "✅ Step 2: Install backend deps"
      cd ../backend
      pip install --upgrade pip
      pip install -r requirements.txt

      echo "✅ Step 3: Install Playwright"
      python -m playwright install chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    rootDir: backend
