services:
  - type: web
    name: archive-saver
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DROPBOX_REFRESH_TOKEN
        fromEnvVar: DROPBOX_REFRESH_TOKEN
      - key: DROPBOX_APP_KEY
        fromEnvVar: DROPBOX_APP_KEY
      - key: DROPBOX_APP_SECRET
        fromEnvVar: DROPBOX_APP_SECRET
      - key: RAINDROP_ACCESS_TOKEN
        fromEnvVar: RAINDROP_ACCESS_TOKEN
